version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/SIDA/frontend"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/SIDA/backend"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/SIDA/backend"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/SIDA/frontend"
    schedule:
      interval: "monthly"