# AWS Deployment Compose

version: "3"

services:
  api:
    image: mtralka/sida:latest-api
    restart: unless-stopped
    container_name: fastapi
    ports: 
      - 80:8000
    env_file: 
      - .env
    
