# PRODUCTION COMPOSE
# modify `environment` variables as needed

version: "3"

services:
  web:
    image: mtralka/sida:latest-frontend
    restart: unless-stopped
    container_name: frontend
    ports:
     - 8080:80
  # ************
  # Uncomment / comment the below / above service to load 
  # SIDA from local repo
  # ************

  # web:
  #   build:
  #     context: ./frontend
  #     dockerfile: prod.dockerfile
  #   restart: unless-stopped
  #   container_name: frontend
  #   ports:
  #    - 8080:80
  #   volumes: 
  #     - ./frontend:/SIDA
  #   environment: 
  #     - VUE_APP_BASE_URL=http://127.0.0.1:8000
  api:
    image: mtralka/sida:latest-api
    # ************
    # Uncomment / comment the below / above service to load 
    # SIDA from local repo
    # ************
    # build:
    #   context: ./backend
    #   dockerfile: back.dockerfile
    restart: unless-stopped
    container_name: fastapi
    ports: 
      - 8000:8000
    volumes: 
      - ./backend:/SIDA
    depends_on: 
      # - redis
      - db
    environment: 
      - DATABASE_URL=postgresql://postgres:admin@postgres:5432/postgres
      - ORIGIN=*
      # if CELERY then use celery
      # celery is currently not in use
      - CELERY=True
  # redis:
  #   image: redis:6.0.9
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  # worker:
  #   build:
  #     context: ./backend
  #     dockerfile: celery.dockerfile
  #   container_name: celery_worker
  #   volumes: 
  #     - ./backend:/SIDA
  #   depends_on: 
  #      - redis
  #   environment: 
  #     - DATABASE_URL=postgresql://postgres:admin@postgres:5432/postgres
  # flower:  
  #   image: mher/flower
  #   container_name: flower
  #   environment: 
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - FLOWER_PORT=8888 
  #   ports:  
  #     - 8888:8888  
  #   depends_on: 
  #     - redis
  db:
    image: postgres:11
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./backend/db/postgres:/var/lib/postgresql/data
    links:
      - pgadmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 5050:80
    volumes:
      - ./backend/db/pgadmin:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
