# DEV COMPOSE
# live update and independent containers

version: "3"

services:
  web:
    build:
      context: ./frontend
      dockerfile: front.dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes: 
      - ./frontend:/SIDA/frontend
    command: npm run dev
  api:
    build:
      context: ./backend
      dockerfile: back.dockerfile
    restart: unless-stopped
    ports: 
      - 8000:8000
    volumes: 
      - ./backend:/SIDA/backend