version: "3"

networks:
  t2_proxy:
    external:
      name: t2_proxy

services:
  web:
    build:
      context: ./frontend
      dockerfile: prod.dockerfile
    restart: unless-stopped
    container_name: frontend
    volumes: 
      - ./frontend:/SIDA
    networks:
      - t2_proxy
      - default
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.personal_web-rtr.entrypoints=https"
      - "traefik.http.routers.personal_web-rtr.rule=Host(`SIDA.$DOMAINNAME`)"
      - "traefik.http.routers.personal_web-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.personal_web-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.personal_web-rtr.service=personal_web-svc"
      - "traefik.http.services.personal_web-svc.loadbalancer.server.port=80"
  api:
    build:
      context: ./backend
      dockerfile: back.dockerfile
    restart: unless-stopped
    container_name: fastapi
    ports: 
      - 8000:8000
    volumes: 
      - ./backend:/SIDA
    depends_on: 
      - redis
      - db
    environment: 
      - DATABASE_URL=postgresql://postgres:admin@postgres:5432/postgres

  redis:
    image: redis:6.0.9
    container_name: redis
    ports:
      - "6379:6379"
  worker:
    build:
      context: ./backend
      dockerfile: celery.dockerfile
    container_name: celery_worker
    volumes: 
      - ./backend:/SIDA
    depends_on: 
       - redis
    environment: 
      - DATABASE_URL=postgresql://postgres:admin@postgres:5432/postgres
  flower:  
    image: mher/flower
    container_name: flower
    environment: 
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888 
    ports:  
      - 8888:8888  
    depends_on: 
      - redis
  db:
    image: postgres:11
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./backend/db/postgres:/var/lib/postgresql/data
    links:
      - pgadmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 5050:80
    volumes:
      - ./backend/db/pgadmin:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
