# DEV COMPOSE
# live update and independent containers

version: "3"

services:
  # web:
  #   build:
  #     context: ./frontend
  #     dockerfile: front.dockerfile
  #   restart: unless-stopped
  #   container_name: frontend
  #   ports:
  #    - 3000:3000
  #   volumes: 
  #     - ./frontend:/SIDA
  #   command: npm run dev
    # note auto-reload w/ vite \
    # doesn't work so hot through docker (config issue?)
    # Normally, I disable this container and work locally
  api:
    build:
      context: ./backend
      dockerfile: back.dockerfile
    restart: unless-stopped
    container_name: fastapi
    ports: 
      - 8000:8000
    volumes: 
      - ./backend:/SIDA
    depends_on: 
      - redis
      - db
    environment: 
      - DATABASE_URL=postgresql://postgres:admin@postgres:5432/postgres

  redis:
    image: redis:6.0.9
    container_name: redis
    ports:
      - "6379:6379"
  worker:
    build:
      context: ./backend
      dockerfile: celery.dockerfile
    container_name: celery_worker
    volumes: 
      - ./backend:/SIDA
    depends_on: 
       - redis
    environment: 
      - DATABASE_URL=postgresql://postgres:admin@postgres:5432/postgres
  flower:  
    image: mher/flower
    container_name: flower
    environment: 
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888 
    ports:  
      - 8888:8888  
    depends_on: 
      - redis
  db:
    image: postgres:11
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./backend/db/postgres:/var/lib/postgresql/data
    links:
      - pgadmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 5050:80
    volumes:
      - ./backend/db/pgadmin:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
