# AWS Deployment Compose

version: "3"

services:
  api:
    image: mtralka/sida:latest-api
    restart: unless-stopped
    container_name: fastapi
    ports: 
      - 8000:8000
    environment: 
      - ORIGIN=*
    
